<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="chassis">
  <!-- Base Properties -->
  <xacro:property name="mass_base" value="10" />
  <xacro:property name="base_x_size" value="1.66000" />
  <xacro:property name="base_y_size" value="0.60000" />
  <xacro:property name="base_z_size" value="0.66000" />

  <xacro:property name="wheelbase" value="1.22" />
  <xacro:property name="track" value="1.23" />

  <!-- Wheel Mounting Positions -->
  <xacro:property name="ground_clearance" value="0.19" />
  <xacro:property name="wheel_x_offset" value="0.0" />
  <xacro:property name="wheel_y_offset" value="0.1" />

  <!-- LIDAR Properties -->
  <xacro:property name="lidar_ground_clearance" value="0.69" />
  <xacro:property name="lidar_x_offset" value="0.4" />

  <xacro:macro name="chassis">
    <!-- Base footprint is on the ground under the robot -->
    <link name="base_footprint"/>

    <gazebo reference="base_link">
      <material>Gazebo/Grey</material>
    </gazebo>
    <!-- Base link is the center of the robot's bottom plate -->
    <link name="base_link">
      <visual>
        <origin xyz="-0.5 -0.04 -0.06" rpy="0 0 ${M_PI/2.0}" />
        <geometry>
          <!--<box size="${base_x_size} ${base_y_size} ${base_z_size}"/>-->
          <mesh filename="package://robucar_description/meshes/robufast_frame.dae"/>
        </geometry>
        <material name="grey">
          <color rgba="0.6 0.6 0.6 1"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <box size="${base_x_size} ${base_y_size} ${base_z_size}"/>
        </geometry>
      </collision>
    </link>
    <joint name="base_footprint_joint" type="fixed">
      <origin xyz="0 0 ${ground_clearance + base_z_size/2}" rpy="0 0 0" />
      <child link="base_link" />
      <parent link="base_footprint" />
    </joint>

    <!-- Interial link stores the robot's inertial information -->
    <link name="inertial_link">
      <inertial>
        <mass value="${mass_base}" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.21666666666666667" ixy="0" ixz="0"
                 iyy="0.8416666666666667" iyz="0"
                 izz="1.0416666666666667" />
      </inertial>
    </link>

    <joint name="inertial_joint" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <parent link="base_link" />
      <child link="inertial_link" />
    </joint>
  </xacro:macro>
</robot>
