<?xml version="1.0"?>

<robot name="robucar" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:arg name="laser_enabled" default="false" />
  <xacro:arg name="camera_enabled" default="false" />
  <xacro:arg name="navsat_enabled" default="false" />

  <xacro:include filename="$(find robucar_description)/urdf/wheel_steered.xacro" />
  <xacro:include filename="$(find robucar_description)/urdf/chassis.xacro" />

  <xacro:property name="M_PI" value="3.14159"/>

  <xacro:macro name="robucar">

    <xacro:chassis/>

    <!-- IMU Link is the standard mounting position for the IMU.-->
    <link name="imu_link"/>
    <joint name="imu_joint" type="fixed">
      <origin xyz="0.35 0 0.1" rpy="0 0 0" />
      <parent link="base_link" />
      <child link="imu_link" />
    </joint>

    <!-- Wheel macros -->
    <xacro:wheel_steered wheel_prefix="front_left" parent_link="base_link" wheel_origin_y="${wheel_y_offset}"  left_right="-1">
      <origin xyz="${wheelbase/2+wheel_x_offset} ${track/2-wheel_y_offset} ${-base_z_size/2 + wheel_radius - ground_clearance}" rpy="0 0 0" />
    </xacro:wheel_steered>
    <xacro:wheel_steered wheel_prefix="front_right" parent_link="base_link" wheel_origin_y="${-wheel_y_offset}"  left_right="1">
      <origin xyz="${wheelbase/2+wheel_x_offset} ${-track/2+wheel_y_offset} ${-base_z_size/2 + wheel_radius - ground_clearance}" rpy="0 0 0" />
    </xacro:wheel_steered>
    <xacro:wheel_steered wheel_prefix="rear_left" parent_link="base_link" wheel_origin_y="${wheel_y_offset}"  left_right="-1">
      <origin xyz="${-wheelbase/2+wheel_x_offset} ${track/2-wheel_y_offset} ${-base_z_size/2 + wheel_radius - ground_clearance}" rpy="0 0 0" />
    </xacro:wheel_steered>
    <xacro:wheel_steered wheel_prefix="rear_right" parent_link="base_link" wheel_origin_y="${-wheel_y_offset}"  left_right="1">
      <origin xyz="${-wheelbase/2+wheel_x_offset} ${-track/2+wheel_y_offset} ${-base_z_size/2 + wheel_radius - ground_clearance}" rpy="0 0 0" />
    </xacro:wheel_steered>

    <xacro:if value="$(arg laser_enabled)">
      <xacro:include filename="$(find lms1xx)/urdf/sick_lms1xx.urdf.xacro"/>
      <xacro:sick_lms1xx />
      <joint name="laser_joint" type="fixed">
        <origin xyz="${lidar_x_offset} 0.0 ${lidar_ground_clearance - base_z_size/2 - ground_clearance}" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="laser" />
      </joint>
    </xacro:if>

    <xacro:if value="$(arg camera_enabled)">
      <link name="camera_link"/>
      <joint name="camera_joint" type="fixed">
        <origin xyz="0.35 0 0.41" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="camera_link" />
      </joint>
    </xacro:if>

    <xacro:if value="$(arg navsat_enabled)">
      <link name="navsat_link">
        <inertial>
          <inertia ixx="0.00001" ixy="0.0" ixz="0.0" iyy="0.00001" iyz="0.0" izz="0.00001" />
          <mass value="0.015" />  <!-- [kg] -->
          <origin xyz="0 0 0" rpy="0 0 0" />
        </inertial>
      </link>
      <joint name="navsat_joint" type="revolute">
        <origin xyz="${-wheelbase/2} 0 0.3" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="navsat_link" />
        <limit upper="0" lower="0" effort="0" velocity="0" />
      </joint>
      <!--<joint name="navsat_joint" type="fixed">
        <origin xyz="${-wheelbase/2} 0 0.3" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="navsat_link" />
      </joint>-->
    </xacro:if>


    <!--<link name="velodyne"/>
    <joint name="velodyne_joint" type="fixed">
      <origin xyz="0.0 0.0 1.0" rpy="0 0 0" />
      <parent link="base_link" />
      <child link="velodyne" />
    </joint>-->
  </xacro:macro>
</robot>
